version: 3
services:
  react:
    build:
      context: /frontend
      dockerfile: ./frontend/Dockerfile
    ports:
    - 80:80

  spring:
    build:
      context: /backend
      dockerfile: ./backend/Dockerfile
    ports:
    - 9090:9090