version: '3'
services:
  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - 80:80

  spring:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
    - 9090:9090