server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    format_sql: true
    use_sql_comments: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
---

server:
  port: 9090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    password: ssafy
    username: ssafy
    url: jdbc:mysql://j6b108.p.ssafy.io:3306/mint?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: dev
